from typing import Union, Optional, Any, Iterator, List, Dict, overload

Lite3Scalar = Union[int, float, str, bytes, bool, None]
Lite3Value = Union['Lite3Object', Lite3Scalar]

__version__: str

class Lite3Object:
    def __init__(self, data: bytes, offset: int = ..., type_hint: int = ...) -> None: ...
    
    @property
    def is_null(self) -> bool: ...
    @property
    def is_bool(self) -> bool: ...
    @property
    def is_int(self) -> bool: ...
    @property
    def is_float(self) -> bool: ...
    @property
    def is_str(self) -> bool: ...
    @property
    def is_valid(self) -> bool: ...
    @property
    def is_bytes(self) -> bool: ...
    @property
    def is_object(self) -> bool: ...
    @property
    def is_array(self) -> bool: ...
    
    def __getitem__(self, key: Union[str, int]) -> Lite3Value: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Lite3Value]: ...
    
    def keys(self) -> Iterator[str]: ...
    def values(self) -> Iterator[Lite3Value]: ...
    def items(self) -> Iterator[tuple[str, Lite3Value]]: ...
    
    def to_python(self, *, object_hook: Any = ..., parse_float: Any = ..., 
                  parse_int: Any = ..., parse_constant: Any = ..., 
                  object_pairs_hook: Any = ...) -> Any: ...
    def as_dict(self) -> Dict[str, Any]: ...
    def as_list(self) -> List[Any]: ...

@overload
def loads(data: Union[bytes, str], *, recursive: bool = False, cls: Any = ..., object_hook: Any = ..., 
          parse_float: Any = ..., parse_int: Any = ..., parse_constant: Any = ..., 
          object_pairs_hook: Any = ..., **kwargs: Any) -> Lite3Object: ...
@overload
def loads(data: Union[bytes, str], *, recursive: bool = True, cls: Any = ..., object_hook: Any = ..., 
          parse_float: Any = ..., parse_int: Any = ..., parse_constant: Any = ..., 
          object_pairs_hook: Any = ..., **kwargs: Any) -> Any: ...

def loads(data: Union[bytes, str], *, recursive: bool = False, cls: Any = ..., object_hook: Any = ..., 
          parse_float: Any = ..., parse_int: Any = ..., parse_constant: Any = ..., 
          object_pairs_hook: Any = ..., **kwargs: Any) -> Union[Lite3Object, Any]: ...

def dumps(obj: Any, *, skipkeys: bool = ..., ensure_ascii: bool = ..., check_circular: bool = ..., 
          allow_nan: bool = ..., cls: Any = ..., indent: Union[None, int, str] = ..., 
          separators: Any = ..., default: Any = ..., sort_keys: bool = ..., **kwargs: Any) -> Union[bytes, str]: ...

