from typing import Union, Optional, Any, Iterator, List, Dict, overload

Lite3Scalar = Union[int, float, str, bytes, bool, None]
Lite3Value = Union['Lite3Object', Lite3Scalar]

class Lite3Object:
    def __init__(self, data: bytes, offset: int = ..., type_hint: int = ...) -> None: ...
    
    @property
    def is_null(self) -> bool: ...
    @property
    def is_bool(self) -> bool: ...
    @property
    def is_int(self) -> bool: ...
    @property
    def is_float(self) -> bool: ...
    @property
    def is_str(self) -> bool: ...
    @property
    def is_bytes(self) -> bool: ...
    @property
    def is_object(self) -> bool: ...
    @property
    def is_array(self) -> bool: ...
    
    def __getitem__(self, key: Union[str, int]) -> Lite3Value: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Lite3Value]: ...
    
    def to_python(self) -> Any: ...
    def as_dict(self) -> Dict[str, Any]: ...
    def as_list(self) -> List[Any]: ...

@overload
def loads(data: bytes, recursive: bool = False) -> Lite3Object: ...
@overload
def loads(data: bytes, recursive: bool = True) -> Any: ...

def loads(data: bytes, recursive: bool = False) -> Union[Lite3Object, Any]: ...

def dumps(obj: Dict[str, Any]) -> bytes: ...
